### ISSUE TITLE
Question about LLFlow metric results

### ISSUE THREAD

**Issue by allanchan339** [ShenZheng2000/LLIE_Survey#1]
Dear authors, 

Thank you for your effort on review low light enhancement field, and also allow to pre-view via arXiv.

I am interested on a part of metric results, The captured table is from the your esteemed review.

![image](https://user-images.githubusercontent.com/38370649/231413117-dc677981-8f5a-4960-afc7-3ea6ebf060cb.png)

And below is captured from LLFlow paper.

![image](https://user-images.githubusercontent.com/38370649/231413480-3b94ca7e-e1e9-40dc-be02-298c61115b3f.png)
![image](https://user-images.githubusercontent.com/38370649/231413541-85325e9e-1885-4d8f-a3db-a9988e203395.png)

I have found some inconsistencies here. Would you kindly have a moment to provide some clarification about the differences?

**Comment by ShenZheng2000** [comment]
I am utilizing the pretrained model provided by the author of LLFlow for inference, and I have verified that the enhanced image is visually consistent with the LLFlow paper.

As you mentioned, my scores differ from those reported in the LLFlow paper. This could be due to differences in the code used to compute PSNR/SSIM/LPIPS. For instance, there may be variations between scores obtained using Matlab and Python (scikit-image).

Nevertheless, I have employed the same code for computing PSNR/SSIM/LPIPS for all low-light enhancement methods. Although this may lead to score discrepancies from the original paper, it is the only way to compare all methods fairly.

**Comment by allanchan339** [comment]
Hi @ShenZheng2000, 
Thank you for clarifying. I appreciate you double-checking the visual consistency of the enhanced images with the LLFlow paper.

You make a good point that differences in computing metrics (e.g. Matlab NIQE vs. Python's NIQE) could lead to discrepancies in scores between our results and those reported in the original paper. Using the same metrics code for evaluating all methods is indeed the fairest approach for comparison.

To better understand the source of score differences, would you be open to sharing your code for computing the PSNR, SSIM and LPIPS metrics? Having the same metrics code would help determine if the differences stem from code variations or other factors. If the code is not readily shareable, I understand - I just wanted to ask in case it could be helpful for analysis.

Please let me know if you have any other thoughts on this. I appreciate the discussion.

**Comment by ShenZheng2000** [comment]
Hey Allan,

I've just completed uploading the code for score calculations in this [folder](https://github.com/ShenZheng2000/LLIE_Survey/blob/main/Metric). The folder currently contains 4 files:

[BRISQUE.py](https://github.com/ShenZheng2000/LLIE_Survey/blob/main/Metric/BRISQUE.py) for BRISQUE

[SPAQ.py](https://github.com/ShenZheng2000/LLIE_Survey/blob/main/Metric/SPAQ.py) for SPAQ

[ref.py](https://github.com/ShenZheng2000/LLIE_Survey/blob/main/Metric/ref.py) for PSNR, SSIM, and LPIPS

[eff_score.py](https://github.com/ShenZheng2000/LLIE_Survey/blob/main/Metric/eff_score.py) for FLOPs, #Params, and Time.

Additionally, you can find the code for UNIQUE in this [repository](https://github.com/zwx8981/UNIQUE).

Feel free to let me know if you have any questions.

Thanks again for taking an interest in my paper!
