### ISSUE TITLE
Add metric results for LOLv2 dataset ?

### ISSUE THREAD

**Issue by allanchan339** [ShenZheng2000/LLIE_Survey#2]
LOLv2 expands upon the LOL dataset and contains more and varied data. I suggest rerunning your model on LOLv2 to gather additional metrics and provide a more comprehensive analysis.

The LOLv2 dataset can be found here: https://github.com/flyywh/CVPR-2020-Semi-Low-Light

**Comment by ShenZheng2000** [comment]
Thank you, Allan! 

I'm currently traveling, but I'll make an effort to provide the outcome within the next few weeks.
