### ISSUE TITLE
Enhanced images google drive link not working

### ISSUE THREAD

**Issue by eashanadhikarla** [ShenZheng2000/LLIE_Survey#5]
Hey Shen, Thank you for the amazing work. Unfortunately, the google drive link for SICE Mix dataset isn't working anymore. Could you please update it. Thank you very much.

**Comment by ShenZheng2000** [comment]
I've checked, and the link is valid. Could you please double-check on your end?

https://drive.google.com/file/d/1gii4AEyyPp_kagfa7TyugnNPvUhkX84x/view?usp=sharing

**Comment by eashanadhikarla** [comment]
I apologize for the confusion, I meant this link:

"Enhanced images for all baselines are [here](https://drive.google.com/file/d/1lSjZRJi4pOaI0auyB8UjPtTAGSb6UpkT/view?usp=share_link)"

<img width="489" alt="Screenshot 2024-10-09 at 3 18 38 PM" src="https://github.com/user-attachments/assets/7484f020-2fa1-4953-84d7-ecfe2c5d4b2a">

**Comment by ShenZheng2000** [comment]
Could you please check this? Here's the updated download link (it's a large file, over 40GB): https://drive.google.com/file/d/1rFpAwt9Ofh3S9RmQrN-zrUvMGIKtg9Zo/view?usp=sharing

**Comment by eashanadhikarla** [comment]
Yes, this link worked. Thank you so much.
